version: '3.8'

services:
  # PostgreSQL для auth-service
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5434:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL для account-service
  account-db:
    image: postgres:16
    container_name: account-db
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5435:5432"
    volumes:
      - account-db-data:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank"]
      interval: 10s
      timeout: 5s
      retries: 5

  # auth-service (будем собирать из исходников)
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: bank
      SPRING_DATASOURCE_PASSWORD: bankpass
    networks:
      - bank-network

  # account-service
  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8082:8082"
    depends_on:
      account-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://account-db:5432/accountdb
      SPRING_DATASOURCE_USERNAME: bank
      SPRING_DATASOURCE_PASSWORD: bankpass
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  auth-db-data:
  account-db-data: